import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "./_components/footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        {children}

        <Toaster />
        <Footer />
      </body>
    </html>
  )
}
